/*
 * figureFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package Frame;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.SQLException;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

import run.Sql;

/**
 *
 * @author  __USER__
 */
public class figureFrame extends javax.swing.JFrame {

	/** Creates new form figureFrame */
	public figureFrame() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setIconImage(new ImageIcon("图片/logo1.jpg").getImage());
		//
		this.setCursor(createCursor());
		this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		this.setVisible(true);

	}

	public static Cursor createCursor() {
		//String fileName = "img/1.jpg";
		Image cursor = Toolkit.getDefaultToolkit().createImage(
				"src\\images\\subiao1.png");
		return Toolkit.getDefaultToolkit().createCustomCursor(cursor,
				new Point(16, 16), "mycursor");

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		choose4 = new javax.swing.JComboBox();
		choose1 = new javax.swing.JComboBox();
		choose2 = new javax.swing.JComboBox();
		choose3 = new javax.swing.JComboBox();
		jButton6 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u4e09\u56fd\u4e89\u9738");

		jPanel1.setLayout(null);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/roleimg/figure3.front.png"))); // NOI18N
		jPanel1.add(jLabel1);
		jLabel1.setBounds(1210, 760, 100, 130);

		jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/roleimg/figure4.front.png"))); // NOI18N
		jPanel1.add(jLabel9);
		jLabel9.setBounds(1540, 760, 100, 130);

		jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/roleimg/figure1.front.png"))); // NOI18N
		jPanel1.add(jLabel8);
		jLabel8.setBounds(70, 760, 100, 130);

		jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/roleimg/figure2.front.png"))); // NOI18N
		jPanel1.add(jLabel7);
		jLabel7.setBounds(450, 760, 100, 130);

		jButton1.setBackground(new java.awt.Color(239, 239, 239));
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/刘备卡牌.png"))); // NOI18N
		jButton1
				.setToolTipText("\u4ec1\u4e49\uff1a\u6bcf\u56de\u5408\u589e\u52a0200\u5175\u529b");
		jButton1.setBorder(null);
		jButton1.setContentAreaFilled(false);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton1);
		jButton1.setBounds(90, 360, 219, 319);

		jButton2.setBackground(new java.awt.Color(239, 239, 239));
		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/曹操卡牌.png"))); // NOI18N
		jButton2
				.setToolTipText("\u67ad\u96c4\uff1a\u6bcf\u56de\u5408\u83b7\u5f97\u4e00\u5f20\u5361\u724c ");
		jButton2.setBorder(null);
		jButton2.setContentAreaFilled(false);
		jPanel1.add(jButton2);
		jButton2.setBounds(500, 360, 219, 319);

		jButton3.setBackground(new java.awt.Color(239, 239, 239));
		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/孙权卡牌.png"))); // NOI18N
		jButton3
				.setToolTipText("\u5236\u8861\uff1a\u6bcf\u56de\u5408\u89e6\u53d1\u4e00\u6b21\u968f\u673a\u4e8b\u4ef6 ");
		jButton3.setBorder(null);
		jButton3.setContentAreaFilled(false);
		jPanel1.add(jButton3);
		jButton3.setBounds(1610, 360, 219, 319);

		jButton4.setBackground(new java.awt.Color(239, 239, 239));
		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/董卓卡牌.png"))); // NOI18N
		jButton4
				.setToolTipText("\u8089\u6797\uff1a\u5360\u9886\u57ce\u6c60\u53ef\u4ee5\u51cf\u5c1110%\u7684\u5175\u529b");
		jButton4.setBorder(null);
		jButton4.setContentAreaFilled(false);
		jPanel1.add(jButton4);
		jButton4.setBounds(1240, 360, 219, 319);

		jButton5.setBackground(new java.awt.Color(255, 255, 255));
		jButton5.setFont(new java.awt.Font("方正古隶简体", 1, 36));
		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/next.button.png"))); // NOI18N
		jButton5.setBorder(null);
		jButton5.setContentAreaFilled(false);
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton5);
		jButton5.setBounds(800, 790, 360, 70);

		choose4.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"玩家", "人机", "无" }));
		choose4.setBorder(null);
		choose4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				choose4ActionPerformed(evt);
			}
		});
		jPanel1.add(choose4);
		choose4.setBounds(1660, 700, 120, 24);

		choose1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"玩家", "人机", "无" }));
		choose1.setBorder(null);
		choose1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				choose1ActionPerformed(evt);
			}
		});
		jPanel1.add(choose1);
		choose1.setBounds(140, 690, 120, 26);

		choose2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"玩家", "人机", "无" }));
		choose2.setBorder(null);
		choose2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				choose2ActionPerformed(evt);
			}
		});
		jPanel1.add(choose2);
		choose2.setBounds(1300, 690, 120, 24);

		choose3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"玩家", "人机", "无" }));
		choose3.setBorder(null);
		choose3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				choose3ActionPerformed(evt);
			}
		});
		jPanel1.add(choose3);
		choose3.setBounds(550, 690, 120, 26);

		jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/figure.returnButton.png"))); // NOI18N
		jButton6.setContentAreaFilled(false);
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});
		jPanel1.add(jButton6);
		jButton6.setBounds(1655, 20, 180, 70);

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/figureFrame.png"))); // NOI18N
		jPanel1.add(jLabel6);
		jLabel6.setBounds(0, 0, 1870, 970);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1873,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 970,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new mainFrame().setVisible(true);
		setVisible(false);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void choose3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			Sql sql = new Sql();
			if (choose3.getSelectedItem().toString().equals("玩家")) {
				sql.setType(1, 2);
			}
			if (choose3.getSelectedItem().toString().equals("人机")) {
				sql.setType(2, 2);
			}
			if (choose3.getSelectedItem().toString().equals("无")) {
				sql.setType(0, 2);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void choose4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			Sql sql = new Sql();
			if (choose4.getSelectedItem().toString().equals("玩家")) {
				sql.setType(1, 4);
			}
			if (choose4.getSelectedItem().toString().equals("人机")) {
				sql.setType(2, 4);
			}
			if (choose4.getSelectedItem().toString().equals("无")) {
				sql.setType(0, 4);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void choose2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			Sql sql = new Sql();
			if (choose2.getSelectedItem().toString().equals("玩家")) {
				sql.setType(1, 3);
			}
			if (choose2.getSelectedItem().toString().equals("人机")) {
				sql.setType(2, 3);
			}
			if (choose2.getSelectedItem().toString().equals("无")) {
				sql.setType(0, 3);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void choose1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			Sql sql = new Sql();
			if (choose1.getSelectedItem().toString().equals("玩家")) {
				sql.setType(1, 1);
				System.out.println("我是玩家");
			}
			if (choose1.getSelectedItem().toString().equals("人机")) {
				sql.setType(2, 1);
				System.out.println("我是人机");
			}
			if (choose1.getSelectedItem().toString().equals("无")) {
				sql.setType(0, 1);
				System.out.println("我是无");
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new PersonmapFrame2().setVisible(true);
		Sql sql = new Sql();
		try {
			//先格式化
			//后排序

			sql.type();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		setVisible(false);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new figureFrame().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JComboBox choose1;
	private javax.swing.JComboBox choose2;
	private javax.swing.JComboBox choose3;
	private javax.swing.JComboBox choose4;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}