/*
 * List.java
 *
 * Created on __DATE__, __TIME__
 */

package Frame;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.ImageIcon;

import function.GameFunction;
import run.Sql;

/**
 *
 * @author  __USER__
 */
public class List extends javax.swing.JFrame {

	/** Creates new form List */
	public List() {
		initComponents();
		this.jScrollPane1.getViewport().setOpaque(false);
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		this.setIconImage(new ImageIcon("图片/logo1.jpg").getImage());
		GameFunction g = new GameFunction();
//		
		g.connection();
		ArrayList<Integer> siteuserid1 = new ArrayList<Integer>();
		ArrayList<Integer> sitetime1 = new ArrayList<Integer>();
		sitetime1 = g.getTime();
		siteuserid1 = g.getUserId();
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "第一名", siteuserid1.get(0), sitetime1.get(0)+"分钟" }, { "第二名", siteuserid1.get(1), sitetime1.get(1)+"分钟" },
						{ "第三名", siteuserid1.get(2), sitetime1.get(2)+"分钟" }, {"第四名", siteuserid1.get(3), sitetime1.get(3)+"分钟" },
						{"第五名", siteuserid1.get(4), sitetime1.get(4)+"分钟" }, { "第六名", siteuserid1.get(5), sitetime1.get(5)+"分钟" },
						{ "第七名", siteuserid1.get(6), sitetime1.get(6)+"分钟" }, { "第八名", siteuserid1.get(7), sitetime1.get(7)+"分钟" },
						{ "第九名", siteuserid1.get(8), sitetime1.get(8)+"分钟" }, { "第十名", siteuserid1.get(9), sitetime1.get(9)+"分钟" } },
				new String[] { "排名", "ID", "存活时间" }));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setLayout(null);

		jScrollPane1.setBackground(new java.awt.Color(0, 153, 153));
		jScrollPane1.setBorder(null);
		jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
		jScrollPane1.setAlignmentX((float) 1.0);
		jScrollPane1.setOpaque(false);

		jTable1.setBackground(new java.awt.Color(102, 102, 102));
		jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(
				javax.swing.border.BevelBorder.RAISED, java.awt.Color.black,
				java.awt.Color.black, java.awt.Color.black,
				java.awt.Color.black));
		jTable1.setFont(new java.awt.Font("楷体", 1, 36));
		
		jTable1.setGridColor(new java.awt.Color(255, 255, 255));
		jTable1.setOpaque(false);
		jTable1.setRowHeight(50);
		jTable1.setRowSelectionAllowed(false);
		jScrollPane1.setViewportView(jTable1);

		jPanel1.add(jScrollPane1);
		jScrollPane1.setBounds(530, 170, 600, 540);
		jPanel1.add(jLabel2);
		jLabel2.setBounds(30, 40, 200, 160);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/listFrame.png"))); // NOI18N
		jLabel1.setAlignmentX((float) 11.0);
		jPanel1.add(jLabel1);
		jLabel1.setBounds(0, 0, 1873, 970);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1873,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new List().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	// End of variables declaration//GEN-END:variables

}